### ISSUE TITLE
Find Egyptian Background

### ISSUE THREAD

**Issue by fergus-g** [SchoolOfCode/week-1-hackathon-room-5-bc18-wk1#2]
Find an image we can use as our background and add it to scratch. Ideally cartoony

**Comment by fergus-g** [comment]
![egypt-pharaoh-tomb-treasury-cartoon-with-warriors-masks-armed-spears_1441-2682](https://github.com/user-attachments/assets/f2404054-d558-4f5d-9414-e69c2c61795b)

**Comment by fergus-g** [comment]
I found this image.  I think it could work really well.  We would just need to alter our structure slightly.  We can just have players clicked on the objects and have the key be revealed when the clicked the right one.

**Comment by pepland** [comment]
Very nice!
